### ISSUE TITLE
Questions about the dataset used in Table A.4 of the paper.

### ISSUE THREAD

**Issue by shy2000** [facebookresearch/egolifter#6]
Thanks for ur wonderful work! 
I have some questions about Table A.4 in the paper. Is the dataset used in this table read by replica_semantic.py ？And what the image stride value was?

**Comment by georgegu1997** [comment]
Hi, thanks for your interest!

> Is the dataset used in this table read by replica_semantic.py

Yes

> And what the image stride value was?

It was 1, which means we used all images in the training set to train.

**Comment by shy2000** [comment]
Thank you so much for your reply! 
So when you trained the features by contrastive lifting,  you also used the whole training set?

**Comment by georgegu1997** [comment]
> So when you trained the features by contrastive lifting, you also used the whole training set?

Yes, that's correct.

**Comment by shy2000** [comment]
Got it, thanks ^_^
