### ISSUE TITLE
Question about some of the sequences

### ISSUE THREAD

**Issue by SunghwanHong** [facebookresearch/egolifter#9]
Hi Qiao @georgegu1997,

Again, I am highly appreciated for all the kind answers. 
I noticed that I can not retrieve the depth and segmentation for some of the sequences. 
For example,  while I can retrieve the RGB images and pose for "Apartment_release_clean_seq131_M1292", segmentation and depth map are not available even though there is depth_images.vrs and segmentations.vrs in the folder I downloaded. 

However, this does not occur with some of the other scenes, such as "Apartment_release_multiskeleton_party_seq101_M1292"

This is pretty weird to me since those vrs files are already in the adt folder but when I am to preprocess them for 3dgs, somehow some of the sequences can not retrieve the segmentation and depth results..

Do you have any idea what's going on with this? 

Thanks!

**Comment by georgegu1997** [comment]
I'm not sure about the depth vrs, but for the segmentation ground truth, I did notice the same thing for the ADT sequences. For some ADT sequences, only a part (a certain continuous chunk) has corresponding segmentation labels. In the process script, I wrote [a few checks](https://github.com/facebookresearch/egolifter/blob/main/scripts/process_adt_3dgs.py#L304) for them and the EgoLifter experiments only used the frames with segmentation ground truth. 

I didn't dig out why this happens - I think maybe the pose tracker didn't work well for some chunks during data collection, which results in wrong segmentation maps that are then filtered out. I think you can further ask [here](https://github.com/facebookresearch/projectaria_tools/issues).

**Comment by SunghwanHong** [comment]
Hi @georgegu1997,

I've been trying to solve the issue the whole day yesterday, but I still couldn't find a solution haha.. 
I've checked whether I downloaded properly (which should've, because I simply used the downloader..) 
Also, as in your code to retrieve segmentation map, it's just using the same code from aria official documents and I have no clue what could've been wrong. I know you might also not have any clue on this, but do you have any idea what could've caused this?

**Comment by georgegu1997** [comment]
I think [this comment](https://github.com/facebookresearch/projectaria_tools/issues/149#issuecomment-2466462261) should answer your question. We need Meta people to reply about how to fix it.

**Comment by SunghwanHong** [comment]
Thank you Qiao! The issue is now solved and I'm closing this
